export const COMPONENT_IDS = {
  AGE_PAGE_YES_BUTTON: 'age-page-yes-button',
  AGE_PAGE_NO_BUTTON: 'age-page-no-button',
  SIGN_IN_FORM_EMAIL: 'sign-in-form-email',
  SIGN_IN_FORM_PASSWORD: 'sign-in-form-password',
  SIGN_IN_FORM_SUBMIT: 'sign-in-form-submit',
  NAVBAR_CURRENT_USER: 'navbar-current-user',
  NAVBAR_SIGN_OUT: 'navbar-sign-out',
  LOGIN_DROPDOWN: 'login-dropdown',
  LOGIN_DROPDOWN_SIGN_IN: 'login-dropdown-sign-in',
  HELP_BUTTON: 'help-button',
  PROFILE: 'profile',
  CONFIGURE_HACC: 'configure-hacc',
  HACC_WIDGET_ADD_CHALLENGE_BUTTON: 'add-challenge-button',
  HACC_WIDGET_ADD_SKILL_BUTTON: 'add-skill-button',
  HACC_WIDGET_ADD_TOOL_BUTTON: 'add-tool-button',
  HACC_WIDGET_VIEW_TEAMS_BUTTON: 'view-teams-button',

  ADD_CHALLENGE_TITLE: 'add-challenge-title',
  ADD_CHALLENGE_DESCRIPTION: 'add-challenge-description',
  ADD_CHALLENGE_SUBMISSION_DETAIL: 'add-challenge-submission-detail',
  ADD_CHALLENGE_PITCH: 'add-challenge-pitch',
  ADD_CHALLENGE_SUBMIT: 'add-challenge-submit',
  EDIT_CHALLENGE_BUTTON: 'edit-challenge-button',
  EDIT_CHALLENGE_DESCRIPTION: 'edit-challenge-description',
  EDIT_CHALLENGE_SUBMISSION_DETAIL: 'edit-challenge-submission-detail',
  EDIT_CHALLENGE_PITCH: 'edit-challenge-pitch',
  EDIT_CHALLENGE_SUBMIT: 'edit-challenge-submit',

  ADD_SKILL_NAME: 'add-skill-name',
  ADD_SKILL_DESCRIPTION: 'add-skill-description',
  ADD_SKILL_SUBMIT: 'add-challenge-submit',
  EDIT_SKILL_BUTTON: 'edit-skill-button',
  EDIT_SKILL_NAME: 'edit-skill-name',
  EDIT_SKILL_DESCRIPTION: 'edit-skill-description',
  EDIT_SKILL_SUBMIT: 'edit-skill-submit',

  ADD_TOOL_NAME: 'add-tool-name',
  ADD_TOOL_DESCRIPTION: 'add-tool-description',
  ADD_TOOL_SUBMIT: 'add-tool-submit',

  PARTICIPATION_FORM_FIRST_NAME: 'participation-form-first-name',
  PARTICIPATION_FORM_LAST_NAME: 'participation-form-last-name',
  PARTICIPATION_FORM_AGREE_BUTTON: 'participation-form-agree-button',
  PARTICIPATION_FORM_SUBMIT: 'participation-form-submit',
  FILTER_NON_COMPLIANT: 'filter-non-compliant',
  FILTER_NO_DEV_POST: 'filter-no-dev-post',
  FILTER_NO_GITHUB: 'filter_no_github',
  FILTER_NONE: 'filter-none',
  DOWNLOAD_TEAM_CAPTAIN_EMAILS: 'download-team-captain-emails',
  SUGGEST_TOOL_SKILL_BUTTON: 'suggest-tool-skill-button',
  SUGGEST_TOOL_SKILL_SELECT: 'suggest-tool-skill-select',
  SUGGEST_TOOL_SKILL_NAME: 'suggest-tool-skill-name',
  SUGGEST_TOOL_SKILL_DESCRIPTION: 'suggest-tool-skill-description',
  SUGGEST_TOOL_SKILL_SUBMIT: 'suggest-tool-skill-submit',
  CREATE_PROFILE_LINKEDIN: 'create-profile-linkedin',
  CREATE_PROFILE_ABOUTME: 'create-profile-aboutme',
  CREATE_PROFILE_CHALLENGES: 'create-profile-challenges',
  CREATE_PROFILE_SUBMIT: 'create-profile-submit',
  LIST_PARTICIPANTS: 'list-participants',
};
