export const COMPONENT_IDS = {
  AGE_PAGE_YES_BUTTON: 'age-page-yes-button',
  AGE_PAGE_NO_BUTTON: 'age-page-no-button',
  SIGN_IN_FORM_EMAIL: 'sign-in-form-email',
  SIGN_IN_FORM_PASSWORD: 'sign-in-form-password',
  SIGN_IN_FORM_SUBMIT: 'sign-in-form-submit',
  NAVBAR_TOGGLE: 'button.navbar-toggler',
  NAVBAR_CURRENT_USER: 'navbar-current-user',
  NAVBAR_SIGN_OUT: 'navbar-sign-out',
  LOGIN_DROPDOWN: 'login-dropdown',
  LOGIN_DROPDOWN_SIGN_IN: 'login-dropdown-sign-in',
  HELP_BUTTON: 'help-button',
  PROFILE: 'profile',
  CONFIGURE_HACC: 'configure-hacc',
  UPDATE_MP: 'update-mp',
  CREATE_TEAM: 'create-team',

  HACC_WIDGET_NAV_CHALLENGE: 'custom-nav-challenge',
  HACC_WIDGET_NAV_SKILL: 'custom-nav-skill',
  HACC_WIDGET_NAV_TOOl: 'custom-nav-tool',
  HACC_WIDGET_CUSTOM_SWITCH_TEAMS: 'custom-switch-teams',
  HACC_WIDGET_CUSTOM_SWITCH_CHALLENGES: 'custom-switch-challenges',
  HACC_WIDGET_ADD_CHALLENGE_BUTTON: 'add-challenge-button',
  HACC_WIDGET_ADD_SKILL_BUTTON: 'add-skill-button',
  HACC_WIDGET_ADD_TOOL_BUTTON: 'add-tool-button',
  EDIT_CHALLENGE_BUTTON: 'edit-challenge-button',
  EDIT_SKILL_BUTTON: 'edit-skill-button',
  EDIT_TOOL_BUTTON: 'edit-tool-button',
  DELETE_CHALLENGE_BUTTON: 'delete-challenge-button',
  DELETE_SKILL_BUTTON: 'delete-skill-button',
  DELETE_TOOL_BUTTON: 'delete-tool-button',

  ADD_CHALLENGE_TITLE: 'add-challenge-title',
  ADD_CHALLENGE_DESCRIPTION: 'add-challenge-description',
  ADD_CHALLENGE_SUBMISSION_DETAIL: 'add-challenge-submission-detail',
  ADD_CHALLENGE_PITCH: 'add-challenge-pitch',
  ADD_CHALLENGE_SUBMIT: 'add-challenge-submit',
  EDIT_CHALLENGE_DESCRIPTION: 'edit-challenge-description',
  EDIT_CHALLENGE_SUBMISSION_DETAIL: 'edit-challenge-submission-detail',
  EDIT_CHALLENGE_PITCH: 'edit-challenge-pitch',
  EDIT_CHALLENGE_SUBMIT: 'edit-challenge-submit',

  ADD_SKILL_NAME: 'add-skill-name',
  ADD_SKILL_DESCRIPTION: 'add-skill-description',
  ADD_SKILL_SUBMIT: 'add-challenge-submit',
  EDIT_SKILL_NAME: 'edit-skill-name',
  EDIT_SKILL_DESCRIPTION: 'edit-skill-description',
  EDIT_SKILL_SUBMIT: 'edit-skill-submit',

  ADD_TOOL_NAME: 'add-tool-name',
  ADD_TOOL_DESCRIPTION: 'add-tool-description',
  ADD_TOOL_SUBMIT: 'add-tool-submit',
  EDIT_TOOL_NAME: 'edit-tool-name',
  EDIT_TOOL_DESCRIPTION: 'edit-tool-description',
  EDIT_TOOL_SUBMIT: 'edit-tool-submit',

  PARTICIPATION_FORM_FIRST_NAME: 'participation-form-first-name',
  PARTICIPATION_FORM_LAST_NAME: 'participation-form-last-name',
  PARTICIPATION_FORM_AGREE_BUTTON: 'participation-form-agree-button',
  PARTICIPATION_FORM_SUBMIT: 'participation-form-submit',
  FILTER_NON_COMPLIANT: 'filter-non-compliant',
  FILTER_NO_DEV_POST: 'filter-no-dev-post',
  FILTER_NO_GITHUB: 'filter_no_github',
  FILTER_NONE: 'filter-none',
  DOWNLOAD_TEAM_CAPTAIN_EMAILS: 'download-team-captain-emails',

  SUGGEST_TOOL_SKILL_BUTTON: 'suggest-tool-skill-button',
  SUGGEST_TOOL_SKILL_SELECT: 'suggest-tool-skill-select',
  SUGGEST_TOOL_SKILL_NAME: 'suggest-tool-skill-name',
  SUGGEST_TOOL_SKILL_DESCRIPTION: 'suggest-tool-skill-description',
  SUGGEST_TOOL_SKILL_SUBMIT: 'suggest-tool-skill-submit',

  CREATE_PROFILE_LINKEDIN: 'create-profile-linkedin',
  CREATE_PROFILE_ABOUTME: 'create-profile-aboutme',
  CREATE_PROFILE_CHALLENGES: 'create-profile-challenges',
  CREATE_PROFILE_SUBMIT: 'create-profile-submit',
  LIST_PARTICIPANTS: 'list-participants',
  LIST_PARTICIPANTS_CARD: 'list-participants-card',
  LIST_PARTICIPANTS_ADMIN: 'list-participants-admin',
  LIST_PARTICIPANTS_CARD_ADMIN: 'list-partcipants-card-admin',
  TEAM_INVITATIONS_BUTTON: 'team-invitations-button',
  ALL_TEAM_INVITATIONS_NAV: 'all-team-invitations-button',
  DELETE_ACCOUNT_NAV: 'delete-account-navbar',
  DELETE_ACCOUNT_TEXT: 'delete-account-textfield',
  DELETE_ACCOUNT_SELECT: 'delete-account-select',
  DELETE_ACCOUNT_BUTTON: 'delete account button',

  YOUR_TEAMS_BUTTON: 'your-teams-button',
  YOUR_TEAMS_CARD: 'your-teams-card',
  OPEN_INVITE_PARTICIPANTS: 'open-invite-participants',
  SEE_INTERTESTED_PARTICIPANTS: 'see-interested-participants',
  INVITE_PARTICIPANTS_TEXTFIELD: 'invite-participants-textfield',
  INVITE_PARTICIPANTS_SUBMIT: 'invite-participants-submit',

  SIDEBAR: 'sidebar',
  SIDEBAR_TOGGLE: 'sidebar-toggle',
  SIDEBAR_SIGN_IN: 'sidebar-sign-in',

  SIDEBAR_PROFILE: 'sidebar-profile',
  SIDEBAR_YOUR_TEAMS_BUTTON: 'sidebar-your-teams-button',
  SIDEBAR_LIST_PARTICIPANTS: 'sidebar-list-participants',
  SIDEBAR_SUGGEST_TOOL_SKILL_BUTTON: 'sidebar-suggest-tool-skill-button',
  SIDEBAR_TEAM_INVITATIONS_BUTTON: 'sidebar-team-invitations-button',

  SIDEBAR_CONFIGURE_HACC: 'sidebar-configure-hacc',
  SIDEBAR_UPDATE_MP: 'sidebar-update-mp',
  SIDEBAR_LIST_PARTICIPANTS_ADMIN: 'sidebar-list-participants-admin',
  SIDEBAR_VIEW_TEAMS_BUTTON: 'sidebar-view-teams-button',
  SIDEBAR_ALL_TEAM_INVITATIONS_NAV: 'sidebar-all-team-invitations-nav',
  SIDEBAR_CLOSE_BUTTON: 'sidebar-close-button',

  DUMP_DATABASE: 'dump-database',
  DUMP_TEAM: 'dump-team',
  GOTO_DUMP_DATABASE: 'goto-dump-database',

  TEAM_CARD: 'team-card',
  MEMBER_TEAM_CARD: 'member_team_card',
  TEAM_MEMBERSHIP_WIDGET: 'team-membership-widget',
  EDIT_PROFILE_BUTTON: 'edit-profile-button',

  VIEW_TEAMS_BUTTON: 'view-teams-button',
  VIEW_TEAM_CARD: 'view-teams-card',
  EDIT_TEAM_BUTTON: 'edit-team-button',
  EDIT_TEAM: 'edit-team',
  EDIT_TEAM_BUTTON_ADMIN: 'edit-team-button',
  EDIT_TEAM_SUBMIT_ADMIN: 'edit-team-submit-admin',
  BEST_FIT_TEAM: 'best-fit-team',

  CREATE_TEAM_NAME: 'create-team-name',
  CREATE_TEAM_DESCRIPTION: 'create-team-description',
  CREATE_TEAM_DEVPOST: 'create-team-devpost',
  CREATE_TEAM_AFFILIATION: 'create-team-affiliation',
  CREATE_TEAM_SUBMIT: 'create-team-submit',
  CREATE_TEAM_OPEN: 'create-team-open',
  CREATE_TEAM_CHALLENGE: 'create-team-challenge',
  CREATE_TEAM_SKILLS: 'create-team-skills',
  CREATE_TEAM_TOOLS: 'create-team-tools',
};
