export const COMPONENT_IDS = {
  ADD_CHALLENGE_TITLE: 'add-challenge-title',
  ADD_CHALLENGE_DESCRIPTION: 'add-challenge-description',
  ADD_CHALLENGE_SUBMISSION_DETAIL: 'add-challenge-submission-detail',
  ADD_CHALLENGE_PITCH: 'add-challenge-pitch',
  ADD_CHALLENGE_SUBMIT: 'add-challenge-submit',
  HACC_WIDGET_ADD_CHALLENGE_BUTTON: 'add-challenge-button',
  AGE_PAGE_YES_BUTTON: 'age-page-yes-button',
  AGE_PAGE_NO_BUTTON: 'age-page-no-button',
  SIGN_IN_FORM_EMAIL: 'sign-in-form-email',
  SIGN_IN_FORM_PASSWORD: 'sign-in-form-password',
  SIGN_IN_FORM_SUBMIT: 'sign-in-form-submit',
  NAVBAR_CURRENT_USER: 'navbar-current-user',
  NAVBAR_SIGN_OUT: 'navbar-sign-out',
  LOGIN_DROPDOWN: 'login-dropdown',
  LOGIN_DROPDOWN_SIGN_IN: 'login-dropdown-sign-in',
  HELP_BUTTON: 'help-button',
  MY_PROFILE: 'my-profile',
  CONFIGURE_HACC: 'configure-hacc',
};
