export const PAGE_IDS = {
  MANAGE_HACC_WIDGET_COMPONENT: 'hacc-widget',
  AGE_PAGE: 'age-page',
  HELP_PAGE: 'help-page',
  LANDING: 'landing',
  SIGN_IN: 'sign-in',
  SIGN_OUT: 'sign-out',
  UNDER_AGE_PARTICIPATION_FORM: 'under-age-participation',
  ADD_CHALLENGE: 'add-challenge',
  ADD_SKILL: 'add-skill',
  ADD_TOOL: 'add-tool',
  EDIT_CHALLENGE_PAGE: 'edit-challenge-page',
  VIEW_TEAMS_PAGE: 'view-teams-page',
  PARTICIPATION_FORM: 'participation-form',
  CREATE_PROFILE: 'create-profile',
  SUGGEST_TOOL_SKILL: 'suggest-tool-skill',
  PROFILE_PAGE: 'profile-page',
  TEAM_INVITATIONS_PAGE: 'team-invitations-page',
};
