export const PAGE_IDS = {
  MANAGE_HACC_WIDGET_COMPONENT: 'hacc-widget',
  AGE_PAGE: 'age-page',
  HELP_PAGE: 'help-page',
  LANDING: 'landing',
  SIGN_IN: 'sign-in',
  SIGN_OUT: 'sign-out',
  UNDER_AGE_PARTICIPATION_FORM: 'under-age-participation',
  ADD_CHALLENGE: 'add-challenge',
  ADD_SKILL: 'add-skill',
  ADD_TOOL: 'add-tool',
  EDIT_CHALLENGE_PAGE: 'edit-challenge-page',
  EDIT_SKILL_PAGE: 'edit-skill-page',
  EDIT_TOOL_PAGE: 'edit-tool-page',
  VIEW_TEAMS_PAGE: 'view-teams-page',
  PARTICIPATION_FORM: 'participation-form',
  CREATE_PROFILE: 'create-profile',
  SUGGEST_TOOL_SKILL: 'suggest-tool-skill',
  PROFILE_PAGE: 'profile-page',
  TEAM_INVITATIONS_PAGE: 'team-invitations-page',
  LIST_PARTICIPANTS: 'list-participants',
  UPDATE_MP_COMPLIANT: 'update-mp-compliant',
  DELETE_FORM: 'delete-account',
  LIST_PARTICIPANTS_ADMIN: 'list-participants-admin',
  ALL_TEAM_INVITATIONS: 'all-team-invitations',
  YOUR_TEAMS: 'your-teams',
};
